package io.jpress.module.barrage.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.barrage.model.base.BaseBarrage;

/**
 * Generated by JPress.
 */
@Table(tableName = "barrage", primaryKey = "id")
public class Barrage extends BaseBarrage<Barrage> {

    private static final long serialVersionUID = 1L;

	
}

