package io.jpress.module.barrage.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBarrage<M extends BaseBarrage<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键ID
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 作者的用户ID
     */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

    /**
     * 作者的用户ID
     */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

    /**
     * 弹幕的作者
     */
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

    /**
     * 弹幕的作者
     */
	public java.lang.String getAuthor() {
		return getStr("author");
	}

    /**
     * 弹幕的内容
     */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 弹幕的内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

    /**
     * 排序编号，常用语置顶等
     */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

    /**
     * 排序编号，常用语置顶等
     */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

    /**
     * 状态
     */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

    /**
     * 状态
     */
	public java.lang.String getStatus() {
		return getStr("status");
	}

    /**
     * 发布时间
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 发布时间
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

}

